[project]
name = "20250601-autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.5.7",
    "autogen-ext[openai,redis,docker]>=0.5.7",
    "autogenstudio>=0.4.2.2",
]
